// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsuU1CJnehKvKlKWSq51SwR0EC01_2obM',
    appId: '1:1087590347110:web:fec8cc3d79f545c0cc98a7',
    messagingSenderId: '1087590347110',
    projectId: 'todo-app-314fb',
    authDomain: 'todo-app-314fb.firebaseapp.com',
    storageBucket: 'todo-app-314fb.appspot.com',
    measurementId: 'G-GFYHT26NDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFdf_5i0XX5Tp1p_JXJo44DEoETweL-qM',
    appId: '1:1087590347110:android:15ca022c9f3fd8fecc98a7',
    messagingSenderId: '1087590347110',
    projectId: 'todo-app-314fb',
    storageBucket: 'todo-app-314fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCEVF1iDnTMCZsc1Z_3-uxyBpaXlF8nkw',
    appId: '1:1087590347110:ios:0ef9a2e37dd26573cc98a7',
    messagingSenderId: '1087590347110',
    projectId: 'todo-app-314fb',
    storageBucket: 'todo-app-314fb.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCEVF1iDnTMCZsc1Z_3-uxyBpaXlF8nkw',
    appId: '1:1087590347110:ios:0ef9a2e37dd26573cc98a7',
    messagingSenderId: '1087590347110',
    projectId: 'todo-app-314fb',
    storageBucket: 'todo-app-314fb.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsuU1CJnehKvKlKWSq51SwR0EC01_2obM',
    appId: '1:1087590347110:web:a1e4480890d4f049cc98a7',
    messagingSenderId: '1087590347110',
    projectId: 'todo-app-314fb',
    authDomain: 'todo-app-314fb.firebaseapp.com',
    storageBucket: 'todo-app-314fb.appspot.com',
    measurementId: 'G-LV6LB6DSQQ',
  );
}
